home/urls.py
from django.urls import path, include
from . import views


app_name = 'home'


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models

# AGES = (
#     0, "Select",
#     1, "Below 18",
#     2, "Above 18 and below 30",
#     3, "Above 30 and Below 50",
#     4, "Above 50"
# )

GENDER = (
    (0, "Select"),
    (1, "Male"),
    (2, "Female"),
    (3, "Rather")
)


class Questionnaire(models.Model):
    name = models.CharField(max_length=200)
    gender = models.IntegerField(choices=GENDER, default=0)
    age = models.IntegerField()
    location = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

home/forms.py
from .models import Questionnaire
from django import forms

AGES = (
    0, "Select",
    1, "Below 18",
    2, "Above 18 and below 30",
    3, "Above 30 and Below 50",
    4, "Above 50"
)

GENDER = (
    0, "Select",
    1, "Male",
    2, "Female",
    3, "Rather not Say"
)


class QuestionnaireAdmin(forms.ModelForm):
    class Meta:
        model = Questionnaire
        fields = ('name', 'age', 'location')


class QuestionnaireForm(forms.Form):
    name = forms.CharField(max_length=200)
    gender = forms.IntegerField(choices=GENDER, default=0)
    age = forms.IntegerField(choices=AGES, default=0)
    location = forms.CharField(max_length=200)
    email = forms.EmailField(max_length=200)

home/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'home/index.html', context)


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question Does Not Exist")
    return render(request, 'home/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'home/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'home/detail.html', {
            'question': question,
            'error_message': "You didn't select a Choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('home:results', args=(question.id,)))

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Collection | Home </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->

</head>

<body>
    {% block content %}

    {% endblock %}


    <script src="{% static 'js/jquery/jquery.min.js' %}></script>
    <script src=" {% static 'js/main.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</body>

</html>

home/templates/home/detail.html
{% extends 'base.html' %}
{% block content %}

<a class="btn btn-secondary btn-sm mb-3" href="{% url 'home:index' %}"> Back To Questionnaires </a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'home:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <div class="form-check">
        <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
            value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    </div>
    {% endfor %}

    <input type="submit" value="Submit" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center mb-3"> Data Collection Sample Questionaire </h1>
{% if latest_question_list %}
{% for question in latest_question_list %}

<div class="card mb-3">
    <div class="card-body">
        <p class="lead">{{ forloop.counter}}. {{ question.question_text }}</p>
        {% for choice in question.choice_set.all %}
        <div class="form-check">
            <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
                value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        </div>
        {% endfor %}
        <a href="{% url 'home:detail' question.id %}" class="btn btn-primary btn-sm"> Submit</a>
        <a href="{% url 'home:results' question.id %}" class="btn btn-secondary btn-sm"> Results</a>
    </div>
</div>

{% endfor %}

{% else %}
<p> No Polls Available</p>

{% endif %}


{% endblock %}

home/templates/home/results.html
{% extends 'base.html' %}
{% block content %}

<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
        {{ choice.choice_text }} <span class="badge badge-success float-right">{{ choice.votes }} submit
            {{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'home:index' %}"> Back To Questionnaires</a>
<a class="btn btn-dark" href="{% url 'home:detail' question.id %}"> Submit Again</a>
{% endblock %}